version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pokeapi
      - POSTGRES_USER=userLocalDev
      - POSTGRES_PASSWORD=passwordLocalDev
    ports:
      - "5432:5432"
    networks:
      - bridgenetwork

networks:
  bridgenetwork:
    driver: bridge